apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdh-test 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:  
    argocd/app-selector: rht-gitops.com/janus-argocd=rhdh-test
    backstage.io/kubernetes-id: rhdh-test    
    janus-idp.io/tekton: rhdh-test
    backstage.io/source-location: url:https://github.com/jduimovich/rhdh-test-gitops
    backstage.io/techdocs-ref: dir:.
    gitlab.com/project-slug: https://github.com/jduimovich/rhdh-test-gitops
    quay.io/repository-slug: jduimovich0/bootstrap 
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental